import Head from 'next/head'
import styles from '@styles/Home.module.css'
import Link from 'next/link'
import { Button } from '@material-ui/core'
import useStyles from '@styles/style'

export default function Home() {
  const classes = useStyles()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome!</h1>
      

      <div className='flex-even-30'>
      <Link href='/categories'><Button className={classes.root} >Categories</Button></Link>
      <Link href='/categories/lazy'><Button className={classes.root}>Lazy Categories</Button></Link>
      </div>
      <div className='grid-2'>
        <Link href='/csr'><h2>CSR</h2></Link>
        <Link href='/ssr'><h2>SSR</h2></Link>
        <Link href='/ssg'><h2>SSG</h2></Link>
        <Link href='/isr'><h2>ISR</h2></Link>
      </div>
      <style jsx>{`
        h2:hover{
          cursor: pointer;
          color: darkred
        }
        h1, h2 {
          text-align: center
        }
      `}</style>
    </div>
  )
}
